### ISSUE TITLE
Add GPU support for Guppy

### ISSUE THREAD

**Issue by drpatelh** [nf-core/nanodemux#1]
The pipeline is able to use CPUs only at this point. It would definitely be worth adding GPU support because the speed-up is massive. Im not entirely sure how best to do this with NF and which parameters to use but opinions are more than welcome 😃

**Comment by csawye01** [comment]
Potential to use this Docker container: aryeelab/guppy-gpu

**Comment by csawye01** [comment]
Possibility that the parameter `--device "cuda:all"` can be used with the CPU version of Guppy to utilize a GPU.

**Comment by drpatelh** [comment]
Made some progress here with this PR:
https://github.com/nf-core/nanodemux/pull/4

**Comment by alneberg** [comment]
This seems to be essentially working with PR #4. For singularity I just had to add

```
singularity {
    runOptions="--nv"
}
```
to have access to the cuda drivers.

**Comment by drpatelh** [comment]
Thanks for testing @alneberg :+1:
