### ISSUE TITLE
fastq concatenation expects barcode01 directory exists

### ISSUE THREAD

**Issue by FranBonath** [nf-core/nanodemux#11]
line 239: ```        if [ -d "barcode01" ]```

get Error when running samples that don't contain barcode01 (e.g. my pool contains barcode 16-18)

solved it by replacing line 239 with
```        if ls -d "barcode"*```

but there might be a more beautiful bash solution.

**Comment by drpatelh** [comment]
Thanks for reporting @FranBonath :+1: 
Will be fixed in https://github.com/nf-core/nanodemux/pull/12
